# Generated by Django 4.1.4 on 2023-11-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='De',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastnm', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('job_titl', models.CharField(max_length=30)),
                ('desc_job', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastnm', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('job_titl', models.CharField(max_length=30)),
                ('desc_job', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cv', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
                ('interst', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=30)),
                ('prjct', models.CharField(max_length=30)),
                ('id_de', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='depaninii.de')),
            ],
        ),
    ]
