# Generated by Django 4.1.4 on 2023-12-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depaninii', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='de',
            name='desc_job',
        ),
        migrations.RemoveField(
            model_name='de',
            name='job_titl',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='desc_job',
        ),
        migrations.RemoveField(
            model_name='ds',
            name='job_titl',
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('id_ds', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='depaninii.ds')),
            ],
        ),
    ]
